# Generated by Django 2.1.7 on 2019-04-09 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190409_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 13, 15, 52, 18831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
