# Generated by Django 2.1.7 on 2019-04-09 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20190409_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 13, 18, 3, 812918, tzinfo=utc)),
        ),
    ]
