# Generated by Django 2.1.7 on 2019-04-15 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_auto_20190412_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='faturamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='quantidade_pessoas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 12, 20, 47, 754868, tzinfo=utc)),
        ),
    ]
